### ISSUE TITLE
How to use sidebar?

### ISSUE THREAD

**Issue by vittore** [ekino/EkinoWordpressBundle#109]
Hi,

first of all thanks for hard work. Bundle&wordpress plugin are great.
I correctly installed bundle and when I call http://mywordpress/symfonyRoute controller and twig template are well parsed.
```jinja
{{ wp_get_header() }}
{{ wp_get_sidebar() }}

<div id="main">
    Your Twig code comes here
</div>

{{ wp_get_footer() }}
```

But a little question: sidebars are empty (header and footer are correct). How to populate sidebars with widgets like other pages?

Where is my mistake?

Thanks in advance.
v.

**Comment by eko** [comment]
Hi @vittore,

Thank you.

Sidebar is displayed by calling Wordpress `get_sidebar()` function. I see that this function can take a name (a page name or something like that) in argument (see: https://developer.wordpress.org/reference/functions/get_sidebar/).

Maybe we could update the `{{ wp_get_sidebar() }}` Twig function to take an optional name as argument?

Can you try to play with it and let me informed if you find a solution on this side please?

**Comment by vittore** [comment]
Interesting idea.
I look into my template (Hueman) and found that's a template customization
(two dynamic sidebars). So I'll investigate.

v.


2016-04-20 21:19 GMT+02:00 Vincent Composieux <notifications@github.com>:

> Hi @vittore <https://github.com/vittore>,
>
> Thank you.
>
> Sidebar is displayed by calling Wordpress get_sidebar() function. I see
> that this function can take a name (a page name or something like that) in
> argument (see:
> https://developer.wordpress.org/reference/functions/get_sidebar/).
>
> Maybe we could update the {{ wp_get_sidebar() }} Twig function to take an
> optional name as argument?
>
> Can you try to play with it and let me informed if you find a solution on
> this side please?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/ekino/EkinoWordpressBundle/issues/109#issuecomment-212566985>
>



-- 
http://www.zen.pn.it
