### ISSUE TITLE
update schema 

### ISSUE THREAD

**Issue by benbet** [ekino/EkinoWordpressBundle#111]
Hi,

I have a problem when I want to update my schema with the command : doctrine:schema:update

ALTER TABLE wp_term_taxonomy ADD CONSTRAINT FK_C4D725F53D8E604F FOREIGN KEY (parent) REFERENCES wp_terms (term_id);
CREATE INDEX IDX_C4D725F53D8E604F ON wp_term_taxonomy (parent);
ALTER TABLE wp_users CHANGE user_pass user_pass VARCHAR(64) DEFAULT '' NOT NULL, CHANGE user_registered user_registered DATETIME DEFAULT '1970-01-01 00:00:00' NOT NULL, CHANGE user_activation_key user_activation_key VARCHAR(60) DEFAULT '' NOT NULL;
ALTER TABLE wp_usermeta CHANGE umeta_id umeta_id INT UNSIGNED AUTO_INCREMENT NOT NULL, CHANGE user_id user_id BIGINT UNSIGNED DEFAULT NULL;
ALTER TABLE wp_usermeta ADD CONSTRAINT FK_F3914E8EA76ED395 FOREIGN KEY (user_id) REFERENCES wp_users (ID);

Error message : 
  [Doctrine\DBAL\Exception\ForeignKeyConstraintViolationException]                                                                                                                              
  An exception occurred while executing 'ALTER TABLE wp_term_taxonomy ADD CONSTRAINT FK_C4D725F53D8E604F FOREIGN KEY (parent) REFERENCES wp_terms (term_id)':                                   
  SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`app2ril`.`#sql-6b7_c3`, CONSTRAINT `FK_C4D725F53D8E604F` FOREIGN KE  
  Y (`parent`) REFERENCES `wp_terms` (`term_id`))  

  [Doctrine\DBAL\Driver\PDOException]                                                                                                                                                           
  SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`app2ril`.`#sql-6b7_c3`, CONSTRAINT `FK_C4D725F53D8E604F` FOREIGN KE  
  Y (`parent`) REFERENCES `wp_terms` (`term_id`))   

  [PDOException]                                                                                                                                                                                
  SQLSTATE[23000]: Integrity constraint violation: 1452 Cannot add or update a child row: a foreign key constraint fails (`app2ril`.`#sql-6b7_c3`, CONSTRAINT `FK_C4D725F53D8E604F` FOREIGN KE  
  Y (`parent`) REFERENCES `wp_terms` (`term_id`))  

My config : 
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        unix_socket: /Applications/MAMP/tmp/mysql/mysql.sock
        mapping_types:
                    enum: string
    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true
        default_entity_manager: symfony

ekino_wordpress:
    #globals: # If you have some custom global variables that WordPress needs
     #   - wp_global_variable_1
     #   - wp_global_variable_2
    table_prefix: "wp_" # If you have a specific Wordpress table prefix
    #wordpress_directory: "/" # If you have a specific Wordpress directory structure
    load_twig_extension: true # If you want to enable native WordPress functions (ie : get_option() => wp_get_option())
    enable_wordpress_listener: false # If you want to disable the WordPress request listener
    security:
        firewall_name: "secured_area" # This is the firewall default name
        login_url: "/wp-login.php" # Absolute URL to the wordpress login page
    services:
        post:
            class: sws\Bundle\FrontBundle\Entity\Post
            repository_class: sws\Bundle\FrontBundle\Entity\PostRepository

Can you help me ?
Regards

**Comment by steffi2392** [comment]
I'm having the same issue. @benbet: were you able to resolve this?
