### ISSUE TITLE
Wordpress index.php

### ISSUE THREAD

**Issue by steffi2392** [ekino/EkinoWordpressBundle#115]
Apologies for the vague question, but I'm out of ideas. 

I'm new-ish to Symfony and am trying to set up this bundle. After following all the setup directions, I am getting an HTTP 500 error when navigating to localhost:8888. 

Is there an extra step to the setup that I may have missed? Any tips on the best way to debug this? 

Thank you!

**Comment by eko** [comment]
@steffi2392, what is the error you got into your web server / symfony's error log?

**Comment by steffi2392** [comment]
[2016-06-11 13:12:16] php.DEBUG: unlink(web/bundles/framework): No such file or directory {"type":2,"file":"/Users/<username>/wordpre    ss_test/symfony/vendor/symfony/symfony/src/Symfony/Component/Filesystem/Filesystem.php","line":178,"level":28928} []

**Comment by steffi2392** [comment]
Actually, that error seems to be completely unrelated to this. 

Redoing the setup: the wordpress homepage loads at every step in the setup up until I change the index.php file (unsurprisingly). At this point, my syfmony logs are no longer updated when I load the page. 

Just checking: should I replace what is automatically in index.php with what you provided, or should I keep the default wp things? 

  define('WP_USE_THEMES', true);
  require(dirname(__FILE__) . '/wp-blog-header.php' );

**Comment by steffi2392** [comment]
Ah ok, found the error: 

PHP Fatal error:  Uncaught Error: Class 'Symfony\Component\ClassLoader\ClassCollectionLoader' not found in /Users/*****/wordpress_test/symfony/var/bootstrap.php.cache:2436

**Comment by steffi2392** [comment]
Hmm, I'm not sure what the root problem was, but I was able to get things working by hardcoding some of the paths in index.php (in case someone encounters something similar later).
