### ISSUE TITLE
Attempted to call function "wp" from the global namespace

### ISSUE THREAD

**Issue by kaizokou** [ekino/EkinoWordpressBundle#118]
I got this error on prod :

Attempted to call function "wp" from the global namespace

I'm using

Symfony 2.8 with ekino/wordpress-bundle dev-master

The code is working fine on localhost both on prod and dev environement.

Here is the wp-blog-header.php file (standard wordpress file)

```
<?php
/**
 * Loads the WordPress environment and template.
 *
 * @package WordPress
 */

if ( !isset($wp_did_header) ) {

    $wp_did_header = true;

    // Load the WordPress library.
    require_once( dirname(__FILE__) . '/wp-load.php' );

    // Set up the WordPress query.
    wp();

    // Load the theme template.
    require_once( ABSPATH . WPINC . '/template-loader.php' );

}
```
If I comment wp() and require_once( ABSPATH . WPINC . '/template-loader.php' ); I don't have the error and I can reach the home page (but I probably gonna have some issues later).

The cache is cleared. Capisfony run composer install just before, so the autoload file should be ok.

Any idea how to fix ?

**Comment by eko** [comment]
Hi @kaizokou,

Sorry but I haven't experienced this issue. Moreover, if code is working fine on your localhost, this is the proof that it is working properly.

I think you missed something on your environment configuration.

Please close this issue if it is not still relevant.

**Comment by kaizokou** [comment]
Hello @eko thank you for your answer.
I think this might be relate to the bundle when I test without this bundle it's working fine.
Once I manage to have this work, I will close thi issue if not related.

Any idea why the call to wp() can cause a namespace error ?

**Comment by kaizokou** [comment]
The the probleme was related to Wordpress and not Ekino Bundle as stated by @eko 
If you have the same error than above, check your wp-config.php file in my case it was a deployment issue that corrupted the file.

I close this ticket.
