### ISSUE TITLE
WordpressResponseSubscriber being called after removal, forced cache clear and fresh checkout

### ISSUE THREAD

**Issue by crmpicco** [ekino/EkinoWordpressBundle#134]
I installed the EkinoWordpressBundle and later removed it as, I believe, I no longer need it.

When I access my application I get this error:

> Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to
> load class "WordpressResponseSubscriber" from namespace
> "Ekino\WordpressBundle\Event\Subscriber". Did you forget a "use"
> statement for another namespace? in
> /private/var/www/cache/prod/classes.php on line 1950

When I delete `classes.php` manually I then get this error:

> Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to
> load class "WordpressResponseSubscriber" from namespace
> "Ekino\WordpressBundle\Event\Subscriber". Did you forget a "use"
> statement for another namespace? in
> /Library/WebServer/Documents/crmpicco/symfony/vendor/symfony/symfony/src/Symfony/Component/EventDispatcher/ContainerAwareEventDispatcher.php
> on line 152

I have a Wordpress app and a Symfony app sitting alongside each other, which was working until I started to strip out references to the EkinoWordpressBundle. See [my other question][2] for some background.

Why is this `WordpressResponseSubscriber` being referenced after I have removed it from my application first with composer and then with a fresh checkout?

  [2]: https://stackoverflow.com/questions/46153327/symfony-and-wordpress-sitting-alongside-each-other-in-webroot

**Comment by eko** [comment]
Hello @crmpicco,

Please also remove the `vendor/ekino/wordpress-bundle` directory and ensure you do not have any configuration under the `ekino_wordpress` section.

There is no other reason for Symfony trying to call this class if any reference on it exists anymore.

Thank you
