### ISSUE TITLE
.htaccess content encoding problem on openshift

### ISSUE THREAD

**Issue by JiboStore** [ekino/EkinoWordpressBundle#55]
Hi, I'm trying out your bundle on vanilla wordpress 4.0 on vanilla openshift php gear, however upon pushing the change, the wordpress front end stopped working (the wp-login still accessible) with content encoding error...
I managed to single out the cause to the .htaccess on master branch. If I still use wordpress .htaccess, the wordpress will still load (of course without symfony and your bundle), however, if I use your .htaccess, this problem occur.

Any idea? I've posted a stackoverflow question here:
http://stackoverflow.com/q/27152340/474330

Thanks!

**Comment by eko** [comment]
Hi @JiboStore,

Is this issue still revelant? If so I will try to give it a look during the week-end.

Thank you!

**Comment by eko** [comment]
Closing this issue as there is no response since more than one month and do not have reproduced it.
