### ISSUE TITLE
User entity override

### ISSUE THREAD

**Issue by edgji** [ekino/EkinoWordpressBundle#71]
I understand there is some functionality to override the default bundle entities but I don't think the implementation is fully integrated with doctrine's metadata mapping. When I run doctrine:schema:update I get SchemaExceptions like 'table with name wp_users' already exists. I'm trying to figure out how to have the default doctrine mapping for an entity to be ignored from the bundle to avoid this issue.

**Comment by eko** [comment]
Hi @edgji,

You can specify a custom Doctrine entity manager for the Wordpress schemas declared here by adding this in your bundle configuration:

```yml
ekino_wordpress:
    entity_manager: wordpress
```

Also, when using `doctrine:schema:update`, you can specify a custom entity manager:

```bash
$ php app/console doctrine:schema:update --em=<entity manager name>
```

This should avoid Symfony to try creating your Wordpress tables again.

Hope it helps.

**Comment by edgji** [comment]
Thanks for pointing me in a direction. I'm still fairly new to Symfony and I'm still wrapping my head around the inner workings of doctrine. I'm still not clear as to what the best way would be to segment the entities as you suggested but I implemented an EntityManager decorator, unfortunately the way Symfony suggests to set it up it replaces the default entity manager. Could I just delete references in the metadata through the entity manager for specific entities?

**Comment by eko** [comment]
Hi @edgji,

The method I give you is the most preferable here as your entities are clearly managed by separated Doctrine entity managers.

Closing this issue as there is no real issue with the bundle here.

Do not hesitate to add your custom implementation on this issue in case it could help some other users later.

Thank you.

**Comment by jstoeffler** [comment]
Just a comment for those who are trying to implement this. It seems better to separate your user data from the user authentication mechanism.

It may seem a counter intuitive object-oriented pattern, but it's easier with this bundle, and it's not bad to separate concerns (data from authentication), meaning you're not tied to this bundle for user management.
