### ISSUE TITLE
Class 'Ekino\WordpressBundle\Entity/model\TermRelationships' does not exist 

### ISSUE THREAD

**Issue by ajeetvarma** [ekino/EkinoWordpressBundle#78]
After installing the bundle when i came for schema update the following error is come . 
                         Class 'Ekino\WordpressBundle\Entity/model\TermRelationships' does not exist 
I do't know why this error is coming  , pls help in this issue  ..

Thanks in advance

**Comment by eko** [comment]
HI @ajeetvarma,

Can you please copy here the full stacktrace of your issue? I can't point out this issue actually.

Thank you for your feedback.

**Comment by ajeetvarma** [comment]
Thanks for response , Actually after implementing the bundle , when i update my schema in terminal console then i found the following error : 
 
"[Doctrine\Common\Persistence\Mapping\MappingException]                       
  Class 'Ekino\WordpressBundle\Entity/model\TermRelationships' does not exist "

while in browser it has no problem . Also i have not used or overrided any entity of the bundle .


Again Thanks ..

**Comment by eko** [comment]
Can you also paste me the configuration you use please?

**Comment by ajeetvarma** [comment]
composer.json : 
         "ekino/wordpress-bundle": "1.0.*@dev"

AppKernal.php:
        new Ekino\WordpressBundle\EkinoWordpressBundle()

routying.yml:
        ekino_wordpress:
            resource: "@EkinoWordpressBundle/Resources/config/routing.xml"

config.yml:
      ekino_wordpress:
               table_prefix: wp_ 
               wordpress_directory: %kernel.root_dir%/../web/blog 
                load_twig_extension: true
               security:
                      firewall_name: secured_area
                      login_url: "/wp-login.php" 
       
That's all the configurations to which i have written .

**Comment by grekpg** [comment]
i have same situation, and don`t use any config i setup  only 

composer.json : 
"ekino/wordpress-bundle": "1.0.*@dev"

AppKernal.php:
new Ekino\WordpressBundle\EkinoWordpressBundle()

routying.yml:
ekino_wordpress:
resource: "@EkinoWordpressBundle/Resources/config/routing.xml"

whe i run php app/console doctrine:schema:update --dump-sql

i get  [Doctrine\Common\Persistence\Mapping\MappingException]                       
  Class 'Ekino\WordpressBundle\Entity/model\TermRelationships' does not exist

**Comment by eko** [comment]
Thank you for these information, I will try to reproduce it.

**Comment by salicio** [comment]
I have the same problem. It starts with the recent release of doctrine/common (v2.5). I've added "doctrine/common": "<2.5" in composer.json until a better solution is found.

**Comment by eko** [comment]
Thank you for this additional information @salicio

**Comment by eko** [comment]
After investigating this point, this is indeed due to new `doctrine/common` 2.5.0 release, and particularly to this pull request: https://github.com/doctrine/common/pull/357

This pull request has introduced some issues when having a subdirectory in `Resources/config/doctrine`.

While waiting for a fix, you can update your `composer.json` dependencies with:
```yml
"doctrine/common": "<2.5"
```

or, you can also disable Doctrine auto mapping in your `app/config.yml` file (it also fix the issue):

```yml
doctrine:
    orm:
        auto_mapping: false
```

I will keep this issue opened in order to follow what's next about it.

Thank you very much for this feedback.

**Comment by ajeetvarma** [comment]
Thanks to all for its suggestion and due to dynamic approach i followed 

                               "doctrine/common": "<2.5"

which worked perfectly .

**Comment by dbpatty** [comment]
Hello,
I've the same problem, I try to set  "doctrine/common": "<2.5" in this way:
"require": {
        "php": ">=5.3.3",
        "symfony/symfony": "~2.4",
        "doctrine/orm": "~2.2,>=2.2.3",
        "doctrine/common": "<2.5",
        "doctrine/doctrine-bundle": "~1.2",
        "twig/extensions": "~1.0",
        "symfony/assetic-bundle": "~2.3",
        "symfony/swiftmailer-bundle": "~2.3",
        "symfony/monolog-bundle": "~2.4",
        "sensio/distribution-bundle": "~2.3",   
        "sensio/framework-extra-bundle": "~3.0",
        "sensio/generator-bundle": "~2.3",
        "incenteev/composer-parameter-handler": "~2.0",
        "hoyes/symfony2-image-manager": "dev-master",
        "liip/oneall-bundle": "dev-master",
        "ext-curl": "*",
        "paypal/merchant-sdk-php":"*",  
        "ekino/wordpress-bundle": "^1.1"
      
    },

but It's the same.
Thank you for your feedback.

Dbpatty

**Comment by eko** [comment]
Hi @dbpatty,

Are you sure you have run the `composer update doctrine/common` command?

I think this version should not have this bug in it.
Otherwise, I will try to reproduce this as soon as possible.

Thank you

**Comment by dbpatty** [comment]
Hi @Eko,
I tried in many way: 
with:
 "name": "symfony/framework-standard-edition",
    "license": "MIT",
    "type": "project",
    "description": "The \"Symfony Standard Edition\" distribution",
    "minimum-stability": "dev",
    "autoload": {
        "psr-0": { "": "src/" }
    },
    "require": {
        "php": ">=5.3.3",
        "symfony/symfony": "~2.4",
        "doctrine/orm": "~2.2,>=2.2.3",
        "doctrine/doctrine-bundle": "~1.2",
        "doctrine/common":"2.5.x-dev",
        "twig/extensions": "~1.0",
        "symfony/assetic-bundle": "~2.3",
        "symfony/swiftmailer-bundle": "~2.3",
        "symfony/monolog-bundle": "~2.4",
        "sensio/distribution-bundle": "~2.3",
        "sensio/framework-extra-bundle": "~3.0",
        "sensio/generator-bundle": "~2.3",
        "incenteev/composer-parameter-handler": "~2.0",
        "hoyes/symfony2-image-manager": "dev-master",
        "liip/oneall-bundle": "dev-master",
        "ext-curl": "*",
        "paypal/merchant-sdk-php":"*",
        "ekino/wordpress-bundle": "^1.1"

    },
...changing-deleting  minimum-stability parameter o doctrine/common value, but the error is the same one.
it Is possible that I don't have a correct configuration of symfony - wp path into the configuration files but I don't know if is the reason.
