### ISSUE TITLE
How override Entity

### ISSUE THREAD

**Issue by tamaragl** [ekino/EkinoWordpressBundle#79]
Hi, I just override Post Entity following your instructions and when I create my Post entity I have the follow problem:

```php
Class "XXX\YYYBundle\Entity\Post" sub class of "Ekino\WordpressBundle\Model\Post" is not a valid entity or mapped super class.
500 Internal Server Error - MappingException
```

and I create my class:
```php
<?php
namespace XXX\YYYBundle\Entity;
use Ekino\WordpressBundle\Model\Post as PostModel;
class Post extends PostModel{
}
```

And my config:
```php
ekino_wordpress:
    table_prefix: wp_ # If you have a specific Wordpress table prefix
    services:
            post:
                class: XXX\YYYBundle\Entity\Post
                repository_class: XXX\YYYBundle\Repository\PostRepository
            term:
                repository_class: XXX\YYYBundle\Repository\TermRepository
```

**Comment by eko** [comment]
Hi @tamaragl, sorry for the late answer, have you found a solution to this issue? If yes, can you close it please?

Otherwise, I will take a look on it.

**Comment by tamaragl** [comment]
Hi eko, I didn't find a solution. And you?

**Comment by eko** [comment]
Hi @tamaragl,

Have you defined the Doctrine schema coming with your entity and added your entity's bundle to the `doctrine.orm.entity_managers.default.mappings` section?

**Comment by joskfg** [comment]
Hi @tamaragl, did you find a solution? Does "doctrine.orm.entity_managers.default.mappings" solved your problem?

**Comment by tamaragl** [comment]
Hi eko,
it was my fault, I had to put new routes(entity, repository...etc) in the orm file to work fine the override.

**Comment by eko** [comment]
You're welcome, thank you. Closing this issue.
