### ISSUE TITLE
Wordpress menu link entry to Symfony

### ISSUE THREAD

**Issue by fruka** [ekino/EkinoWordpressBundle#80]
Bonjour,

Je viens de télécharger et installer tout ce qu'il faut pour utiliser Symfony et Wordpress ensemble en utilisant le tuto décrit là : http://vincent.composieux.fr/article/utiliser-wordpress-et-symfony-ensemble mais je n'arrive pas à comprendre le fonctionnement.
Pour résumer, j'ai un site vitrine simple fait avec Wordpress.
J'ai une application métier faite avec Symfony 2 à intégrer dans ce site via un menu.
Je veux pouvoir faire un lien vers mon application symfony tout en restant dans mon site wordpress (header, footer...).
Mon arborescence Symfony est intégrée à mon répertoire Wordpress.
Je pensais pouvoir faire tout ça en suivant le tuto mais là je sèche.
Ma question est donc simple : est ce possible de faire ce que je veux avec ce bundle? Si oui comment? Sinon, connaissez vous un autre moyen d'arriver à faire cela?

Merci d'avance pour vos réponses.
Cordialement

**Comment by rande** [comment]
Please, can you ask your question in english ?

**Comment by fruka** [comment]
Yes, sorry, i will try...

I just download and install the bundle to use Symfony and Wordpress together following this :http://vincent.composieux.fr/article/use-wordpress-and-symfony-together but i don't understand how it works.

To resume, i have a simple website make with wordpress.
I also have an application in symfony 2 to integrate in this website via a menu.
I would like to create a new item in my menu with a link to my application symfony but i need to stay in my wordpress environment (header, footer...).
My symfony repository is inside my wordpress repository.
I thought i could do that with the tuto but i don't manage it.
My question is simple : is it possible to do that with this bundle? If yes, how? If no, do you know a way to do that?

Thanks a lot!

**Comment by eko** [comment]
Hi @fruka,

Sorry for the delay of my response. Of course you can.

You have to install this `EkinoWordpressBundle` but also the `ekino-wordpress-symfony` Wordpress plugin (available here: https://github.com/ekino/ekino-wordpress-symfony)

This way, you will be able to call the Symfony routing service to generate URLs coming from your Symfony routes:

```php
$url = \symfony_service('router')->generate('your.route.name', array('parameter' => 'value'));
```

Hope it helps, let me know.
