### ISSUE TITLE
PostMeta MappingException

### ISSUE THREAD

**Issue by kasparsj** [ekino/EkinoWordpressBundle#83]
Hi, I'm trying to retrieve latest WordPress blog post inside Symfony2:
```php
$postManager = $this->get('ekino.wordpress.manager.post');
$postRepo = $postManager->getRepository();
$latestPost = $postRepo->createQueryBuilder('p')
       ->addOrderBy('p.date', 'DESC')
       ->addOrderBy('p.id', 'DESC')
       ->setMaxResults(1)
       ->getQuery()
       ->getOneOrNullResult();
```
but getting an error:
```
The class 'Ekino\WordpressBundle\Entity\PostMeta' was not found in the chain configured namespaces Ekino\WordpressBundle\Model
```

**Comment by eko** [comment]
Hi @kasparsj,

Have you correctly added the `EkinoWordpressBundle` to the `doctrine.orm.entity_managers.default.mappings` section or defined `doctrine.orm.auto_mapping` to true?

Thank you

**Comment by eko** [comment]
Hi @kasparsj,

Is this issue still relevant or can we close?

Thank you

**Comment by kasparsj** [comment]
Thanks.
