### ISSUE TITLE
Infinite redirect loop in wordpress multisite

### ISSUE THREAD

**Issue by h3llr4iser** [ekino/EkinoWordpressBundle#91]
I have a infinite redirect loop when trying to load front-end wordpress routes in multisite
wp-config.php
`define('MULTISITE', true);`

http://domain.com -> infinite redirect loop
http://domain.com/category/example -> rinfinite redirect loop
http://domain.com/wp-admin -> i can login in wordpress control panel
http://domain.com/custom-symfony-route -> i can caccess

**Comment by h3llr4iser** [comment]
I found the problem, I have the plugin WordPress MU Domain Mapping and is not compatible

**Comment by eko** [comment]
Hi @h3llr4iser,

I was looking at this issue and can't reproduce ;)

Thank you for these informations, enjoy Symfony & Wordpress.
