### ISSUE TITLE
make the Bundle Symfony 3.0 compatible

### ISSUE THREAD

**Issue by lsmith77** [ekino/EkinoWordpressBundle#95]

**Comment by eko** [comment]
Hi @lsmith77,

This bundle should actually work with Symfony 3.0.

I close this issue, feel free to reopen if you have any particular issue.

Thank you

**Comment by lsmith77** [comment]
hmm .. I do not remember what let me to opening this ticket ... but IIRC I ran into a deprecation when I tried to install it into a Symfony 3 app
