### ISSUE TITLE
Fatal error: Class 'Symfony\Component\ClassLoader\ClassCollectionLoader'

### ISSUE THREAD

**Issue by epci** [ekino/EkinoWordpressBundle#98]
I have an error after editing index.php

Fatal error: Class 'Symfony\Component\ClassLoader\ClassCollectionLoader' not found in /var/www/wordpress-symfony/symfony/var/bootstrap.php.cache on line 2409

I use 
- wordpress 4.4.1
- symfony 3.0.*

**Comment by linkhost** [comment]
$loader = require_once __DIR__.'/../var/bootstrap.php.cache';

replace

$loader = require __DIR__.'/../app/autoload.php';
include_once __DIR__.'/../app/bootstrap.php.cache';

**Comment by epci** [comment]
Tank you, but in sf3, bootstrap.php.cache is in var folder
